name: analytics
description: A new Flutter package project.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  amplitude_flutter: ^3.11.0
  firebase_analytics: ^9.3.8
  logging: ^1.1.1
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
