name: analytics
description: A new Flutter package project.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.7.2
  flutter: ^3.29.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  amplitude_flutter: ^4.3.0
  firebase_analytics: ^11.2.0
  logging: ^1.1.1
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  foundation_lints: ^0.1.0
