minApprovals:
  MEMBER: 1
  COLLABORATOR: 1
mergeMethod: squash
requiredBaseBranches:
- main
- regex: ^release/v\d
requiredLabels:
- automerge
blockingLabels:
- blocked
blockingTitleRegex: '\bWIP\b'
updateBranch: true
reportStatus: true
deleteBranchAfterMerge: true
