minApprovals:
  MEMBER: 1
  COLLABORATOR: 2
requiredBaseBranches:
- main
- regex: ^release/v\d
blockingLabels:
- blocked
blockingTitleRegex: '\bWIP\b'
reportStatus: true
updateBranch: true
deleteBranchAfterMerge: true
mergeMethod: squash
