name: zapify
description: A new Flutter project.
version: 2.1.0+11
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.3.10

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # local packages
  analytics:
    path: 'packages/analytics'
  config_core:
    path: 'packages/config_manager/core'
  config_firebase:
    path: 'packages/config_manager/firebase'

  # personal flutter packages
  error_adapter: ^0.1.0
  logify: ^1.0.0
  simple_nav: ^0.1.0
  state_action_bloc: ^0.1.0

  # third party packages
  app_install_date: ^0.1.1
  call_log: ^4.0.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_core: ^1.24.0
  firebase_crashlytics: ^2.9.0
  firebase_performance: ^0.8.3+3
  firebase_remote_config: ^2.0.20
  flutter_svg: ^1.1.6
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  google_mobile_ads: ^2.3.0
  in_app_review: ^2.0.6
  intl: ^0.17.0
  is_firebase_test_lab_activated: ^2.0.1
  logging: ^1.1.1
  meta: ^1.8.0
  path: ^1.8.0
  permission_handler: ^10.2.0
  phone_number: ^1.0.0
  provider: ^6.0.5
  receive_intent: ^0.2.3
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  sqlbrite: ^2.5.0
  sqflite: ^2.2.8+4
  stack_trace: ^1.10.0
  timeago: ^3.2.2
  timeago_flutter: ^1.1.0
  url_launcher: ^6.1.10


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.0
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
