name: zapify
description: A new Flutter project.
version: 2.2.1+14
publish_to: 'none'

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">= 3.29.2 <4.0.0"

workspace:
  - packages/analytics
  - packages/config_manager/core
  - packages/config_manager/firebase
  - packages/foundation/lints

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # local packages
  analytics: ^0.1.0
  config_core: ^0.1.0
  config_firebase: ^0.1.0

  # personal flutter packages
  error_adapter: ^0.1.0
  logify: ^1.0.0
  simple_nav: ^0.1.0
  state_action_bloc: ^0.1.0

  # third party packages
  app_install_date: ^0.1.5
  call_log: ^5.0.1
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.4
  firebase_performance: ^0.10.1+4
  firebase_remote_config: ^5.4.2
  flutter_svg: ^2.0.17
  freezed_annotation: ^3.0.0
  get_it: ^7.2.0
  google_fonts: ^6.2.1
  google_mobile_ads: ^5.3.1
  in_app_review: ^2.0.9
  intl: ^0.19.0
  logging: ^1.1.1
  meta: ^1.8.0
  path: ^1.8.0
  permission_handler: ^11.4.0
  phone_number: ^2.1.0
  provider: ^6.0.5
  receive_intent: ^0.2.7
  rxdart: ^0.27.7
  shared_preferences: ^2.5.3
  shimmer: ^2.0.0
  sqlbrite: ^2.5.0
  sqflite: ^2.2.8+4
  stack_trace: ^1.10.0
  timeago: ^3.2.2
  timeago_flutter: ^3.0.0
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  foundation_lints: ^0.1.0
  freezed: ^3.0.4
  mocktail: ^0.3.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
