version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/flutter.yml
          parameters: .fvm/fvm_config.json

workflows:
  setup:
    jobs:
      - setup