version: 2.1
orbs:
  flutter: circleci/flutter@1.1.0
jobs:
  distribute:
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          flutter_version: 3.3.1
      - flutter/install_ios_pod
      - flutter/install_ios_gem
      - run:
          command: flutter build ios --release --no-codesign
workflows:
  distribute:
    jobs:
      - distribute