version: 2.1
orbs:
  android: circleci/android@2.1.2
  flutter: circleci/flutter@1.1.0

jobs:
  distribute:
    executor:
      name: android/android-docker
      tag: "2022.09"
    steps:
      - checkout
      - android/accept-licenses
      - flutter/install_sdk_and_pub:
          flutter_version: 3.3.1
      - flutter/install_android_gradle
      - flutter/install_android_gem
      - run:
          name: "Creating google-services.json"
          command: echo $ANDROID_GOOGLE_SERVICES | base64 -d > android/app/google-services.json
      - run:
          name: "Creating android/trilobitech.keystore"
          command: echo $ANDROID_KEYSTORE | base64 -d > android/trilobitech.keystore
      - run:
          name: "Creating secrets.properties"
          command: echo $ANDROID_SECRETS_PROPERTIES | base64 -d > android/secrets.properties
      - run:
          name: "Creating android/gplay.secret.json"
          command: echo $ANDROID_GPLAY_SECRET | base64 -d > android/gplay.secret.json
      - run:
          command: bundle exec fastlane build_bundle
          working_directory: android

workflows:
  distribute-workflow:
    jobs:
      - distribute:
          context: zapify-env