name: ui
description: "A new Flutter package project."
version: 0.1.0

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.2"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  logify: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  foundation_lints: ^0.1.0
  pubspec_gen: ^0.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/
