name: config_core
description: A new Flutter package project.
version: 0.1.0
# homepage:

environment:
  sdk: ^3.7.2
  flutter: ^3.29.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  shared_preferences: ^2.0.15
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  foundation_lints: ^0.1.0

flutter: { }
