source "https://rubygems.org"

plugins_path = File.join(File.dirname(File.dirname(__FILE__)), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)

# https://github.com/fastlane/fastlane/issues/21942#issuecomment-2582202838
gem 'abbrev'
gem 'logger'
gem 'mutex_m'
gem 'csv'
