name: "Android Setup"
description: "Configure Android environment"

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: "zulu"

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
