name: zapify_flavor
description: A new Flutter package project.
version: 0.0.1

publish_to: "none"

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  # local packages
  flavor_core:
    path: ../../core/flavor
  config_manager_core:
    path: ../../core/config_manager
  di_core:
    path: ../../core/di
  analytics_core:
    path: ../../core/analytics
  domain_core:
    path: ../../core/domain
  ext:
    path: ../../core/ext
  banner_core:
    path: ../../core/banner
  config:
    path: ../../config
  resources:
    path: ../../resources

  # personal flutter packages
  state_action_bloc: ^0.1.0

  # third party packages
  amplitude_flutter: ^3.11.0
  app_install_date: ^0.1.2
  firebase_core: ^1.24.0
  firebase_core_platform_interface: 4.5.1
  firebase_crashlytics: ^2.9.0
  firebase_performance: ^0.8.3+3
  firebase_remote_config: ^2.0.20
  firebase_analytics: ^9.3.8
  freezed_annotation: ^2.2.0
  google_mobile_ads: ^2.3.0
  in_app_review: ^2.0.6
  logging: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.2.0
  build_runner: ^2.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.trilobitech.zapify.zapify_flavor
        pluginClass: ZapifyFlavorPlugin
