name: "Flutter Setup"
description: "Configure Flutter environment"

runs:
  using: "composite"
  steps:
    - name: Retrieve Flutter version from FVM config
      uses: kuhnroyal/flutter-fvm-config-action@v1

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: ${{ env.FLUTTER_CHANNEL }}

    - run: flutter pub get
      shell: bash
