// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkJlgTRsKJ3uASLtJ22gd-SuV4GaGAE2U',
    appId: '1:995018310320:web:c5a5c843b26a68bee3f175',
    messagingSenderId: '995018310320',
    projectId: 'zapfy-f575a',
    authDomain: 'zapfy-f575a.firebaseapp.com',
    storageBucket: 'zapfy-f575a.appspot.com',
    measurementId: 'G-PJNYKX5K6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY_DUQGxktxzVeJ0VTF_hb53SE5dXT5tQ',
    appId: '1:995018310320:android:fb7a59ab4a64b6cfe3f175',
    messagingSenderId: '995018310320',
    projectId: 'zapfy-f575a',
    storageBucket: 'zapfy-f575a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlWHL7b4UpxByz7K9kCyGVdmAIh-kb7lY',
    appId: '1:995018310320:ios:f3b02f034f622aa6e3f175',
    messagingSenderId: '995018310320',
    projectId: 'zapfy-f575a',
    storageBucket: 'zapfy-f575a.appspot.com',
    iosClientId: '995018310320-hrabs7m4m0q936du845rgki4516ufjpc.apps.googleusercontent.com',
    iosBundleId: 'com.zapfy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlWHL7b4UpxByz7K9kCyGVdmAIh-kb7lY',
    appId: '1:995018310320:ios:f3b02f034f622aa6e3f175',
    messagingSenderId: '995018310320',
    projectId: 'zapfy-f575a',
    storageBucket: 'zapfy-f575a.appspot.com',
    iosClientId: '995018310320-hrabs7m4m0q936du845rgki4516ufjpc.apps.googleusercontent.com',
    iosBundleId: 'com.zapfy.app',
  );
}
