source "https://rubygems.org"

gem 'cocoapods', '~> 1.16.0'
gem 'activesupport', '>= 6.1.7.3' # https://github.com/advisories/GHSA-pj73-v5mw-pm9j

plugins_path = File.join(File.dirname(File.dirname(__FILE__)), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
