# Shared lanes

$app_name = 'Zapify'
$project_path = File.realpath(File.dirname(File.dirname(__FILE__)))

def flutter(cmd)
  Dir.chdir($project_path) do
    sh("./bin/get-dart-define.sh | xargs flutter #{cmd}")
  end
end

lane :get_changelog do
  is_unreleased_section = false
  changelog_contents = ''

  File.readlines("#{$project_path}/CHANGELOG.md").each do |line|
    if is_unreleased_section
      if line.start_with?('## [')
        break
      end
      changelog_contents += line
    end
    is_unreleased_section = is_unreleased_section || line.start_with?('## [Unreleased]')
  end

  changelog_contents.strip
end
