name: zapify_cli
description: A sample command-line application with basic argument parsing.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

resolution: workspace

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dotenv: ^4.2.0
  get_it: ^8.0.3
  http: ^1.3.0
  image: ^4.5.4
  intl: ^0.19.0
  meta: ^1.16.0
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  foundation_lints: ^0.1.0
  test: ^1.24.0
