name: 'Fastlane Setup'
description: 'Configure Fastlane'

inputs:
  lane:
    description: "The lane that should be executed."
    required: true
  working-directory:
    description: "The relative path from the project root directory to the subdirectory where the fastlane folder is located."
    required: false
    default: "./"

runs:
  using: "composite"
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        working-directory: ${{ inputs.working-directory }}

    - run: bundle exec fastlane "${{ inputs.lane }}"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
  