title: Zapify
google_analytics: G-WS6VJNYSVL

# url: https://trilobitech.com/zapify
languages: ["en-us", "pt-br", "es-es"]
default_lang: "en-us"
lang_from_path: true
exclude_from_localization:
  - "assets"
parallel_localization: true

markdown: kramdown

plugins:
  - jekyll-polyglot

include: ["_pages"]
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
