name: Alls green

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, labeled]

concurrency:
  group: alls-green-${{ github.event.pull_request.head.sha || github.sha }}
  cancel-in-progress: true

jobs:
  alls-green-check:
    runs-on: ubuntu-latest

    steps:
      - name: Wait on checks
        uses: pedrox-hs/all-green-checks@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
