on:
  pull_request:
    types: [opened, reopened, ready_for_review, labeled, edited]
  pull_request_review:
    types: [dismissed]

permissions:
  contents: read
  pull-requests: write

name: Autoapproval workflow

jobs:
  autoapproval:
    name: Autoapproval
    runs-on: ubuntu-latest
    steps:
      - name: Autoapproval
        uses: dkhmelenko/autoapproval@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
