name: Autoapproval

on:
  workflow_run:
    workflows:
      - Alls green
    types:
      - completed

jobs:
  autoapproval:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.pull_requests }}
    permissions:
      contents: read
      pull-requests: write
    uses: pedrox-hs/autoapproval/.github/workflows/try-autoapproval.yml@main
