on: [pull_request]

name: QA Workflow

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0

      - uses: ./.github/actions/flutter

      - name: Setup Firebase Options
        run: |
          tee lib/firebase_options.dart <<EOF
          class DefaultFirebaseOptions {
            static const currentPlatform = null;
          }
          EOF

      - uses: peterfortuin/github-actions-analyze-dart@2dcc207b0d93ca4df53d4497fbdf6e50daf16ab8
        with:
          fail-on-warnings: true
