on: [pull_request]

name: QA Workflow

jobs:
  lint:
    name: Check code standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.5.0

      - name: Setup Flutter SDK
        uses: ./.github/actions/flutter

      - name: Setup Firebase Options
        run: |
          tee lib/firebase_options.dart <<EOF
          class DefaultFirebaseOptions {
            static const currentPlatform = null;
          }
          EOF

      - name: Run dart analyze and check format
        uses: peterfortuin/github-actions-analyze-dart@cf0a8e03a499cc64ffdf146084e978b79c754532
        with:
          fail-on-warnings: true
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.5.0

      - name: Setup Flutter SDK
        uses: ./.github/actions/flutter

      - name: Setup Firebase Options
        run: |
          tee lib/firebase_options.dart <<EOF
          class DefaultFirebaseOptions {
            static const currentPlatform = null;
          }
          EOF

      - name: Run unit tests
        run: flutter test
