on: [pull_request]

name: QA Workflow

jobs:
  lint:
    name: Check code standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Retrieve Flutter version from FVM config
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Install dependencies
        run: flutter pub get

      - name: Setup Firebase Options
        run: |
          tee lib/firebase_options.dart <<EOF
          class DefaultFirebaseOptions {
            static const currentPlatform = null;
          }
          EOF

      - name: Run dart analyze and check format
        uses: zgosalvez/github-actions-analyze-dart@v2
        with:
          fail-on-warnings: true
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Retrieve Flutter version from FVM config
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Install dependencies
        run: flutter pub get

      - name: Setup Firebase Options
        run: |
          tee lib/firebase_options.dart <<EOF
          class DefaultFirebaseOptions {
            static const currentPlatform = null;
          }
          EOF

      - name: Run unit tests
        run: flutter test
