name: Create Release on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  create-release:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.head.ref =~ '^release/v[0-9]+\\.[0-9]+\\.[0-9]+$' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read version from pubspec.yaml
        id: read_version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | tail -n1 | awk '{ print $2}')
          VERSION_NAME=${VERSION%+*}
          echo "VERSION=v$VERSION_NAME" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.16.0
        permissions:
          contents: write
        with:
          name: Release ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          commit: ${{ github.sha }}
          generateReleaseNotes: true
