name: "Distribute Android Flutter app"

on:
  workflow_call:
    inputs:
      environment:
        description: "Distribution environment"
        type: string
        required: true

    secrets:
      ANDROID_BUILD_FILES:
        required: true
      AMPLITUDE_KEY:
        required: true
      FIREBASE_TOKEN:
        required: true
      TESTER_EMAIL:
        required: false

jobs:
  distribute:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - id: versions
        name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "zulu"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: stable
          flutter-version: ${{ steps.versions.outputs.flutter }}

      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: Install dependencies
        run: flutter pub get

      - name: Install Ruby to use Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.versions.outputs.ruby }}
          bundler-cache: true
          working-directory: ./android

      - name: Get Android secrets files
        run: base64 -d <<< ${{ secrets.ANDROID_BUILD_FILES }} | tar xzf -

      - name: Run lane to distribute
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: ${{ vars.TARGET_LANE }}
          options: '{ "tester_email": "${{ secrets.TESTER_EMAIL }}" }'
          subdirectory: ./android
        env:
          ZAPIFY_AMPLITUDE_KEY: ${{ secrets.AMPLITUDE_KEY }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FASTLANE_SKIP_UPDATE_CHECK: true
