name: "Distribute App"

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "Build target platform"
        options:
          - android
          - ios
          - all
        type: choice
        required: true
      environment:
        description: "Distribution environment"
        type: environment
        required: true
      tester_email:
        description: "Distribute to tester email address"
        type: string
        required: false

    secrets:
      FILES:
        required: false
      AMPLITUDE_KEY:
        required: false
      FIREBASE_TOKEN:
        required: false

jobs:
  distribute:
    needs: pre-distribute
    strategy:
      matrix: ${{ fromJSON(needs.pre-distribute.outputs.matrix-definition) }}

    runs-on: ${{ matrix.runs-on }}
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Mask email
        id: tester_email
        if: ${{ github.event.inputs.tester_email != '' }}
        run: |
          # issue https://github.com/actions/runner/issues/475
          # gambi https://github.com/actions/runner/issues/643#issuecomment-708228940

          tester_email=$(jq -r '.inputs.tester_email' $GITHUB_EVENT_PATH)
          echo "::add-mask::$tester_email"
          echo "value=$tester_email" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v3.2.0

      - name: Setup Java
        if: ${{ matrix.platform == 'android' }}
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "zulu"

      - name: Setup Android SDK
        if: ${{ matrix.platform == 'android' }}
        uses: android-actions/setup-android@v2

      - name: Retrieve Flutter version from FVM config
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Install dependencies
        run: flutter pub get

      - name: Get secrets files
        run: base64 -d <<< ${{ secrets.FILES }} | tar xzf -
        
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: ${{ matrix.working-directory }}

      - name: Run lane to distribute
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: ${{ needs.pre-distribute.outputs.lane }}
          options: '{ "tester_email": "${{ steps.tester_email.outputs.value }}" }'
          subdirectory: ${{ matrix.working-directory }}
        env:
          ZAPIFY_AMPLITUDE_KEY: ${{ secrets.AMPLITUDE_KEY }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  pre-distribute:
    runs-on: ubuntu-latest
    outputs:
      matrix-definition: ${{ steps.definition.outputs.matrix }}
      lane: ${{ steps.definition.outputs.channel }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0

      - id: definition
        name: "Prepare distribution"
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment }}
          PLATFORM=${{ github.event.inputs.platform }}

          yaml2json() {
            python -c 'import sys, yaml, json; print(json.dumps(yaml.safe_load(sys.stdin.read())))'
          }

          case "$ENVIRONMENT" in
          production) CHANNEL=release_distribute ;;
          firebase-distribution) CHANNEL=firebase_distribute ;;
          *) echo "Invalid environment $ENVIRONMENT"; exit 1 ;;
          esac

          JQ_EXPR=$(cat <<EOF
            del( .[] | select(.platform != "$PLATFORM" and "$PLATFORM" != "all"))
          EOF
          )
          MATRIX="{ \"include\": $(yaml2json < .github/distribute-platforms.yml | jq -Mc "$JQ_EXPR") }"

          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
          echo "channel=$CHANNEL" >> $GITHUB_OUTPUT
