name: "Distribute app"

on:
  workflow_call:
    inputs:
      platform:
        description: "Build target platform"
        type: string
        required: true
      environment:
        description: "Distribution environment"
        type: string
        required: true

    secrets:
      ANDROID_BUILD_FILES:
        required: false
      IOS_BUILD_FILES:
        required: false
      AMPLITUDE_KEY:
        required: true
      TESTER_EMAIL:
        required: false
      FIREBASE_TOKEN:
        required: false

jobs:
  distribute:
    needs: pre-distribute
    strategy:
      matrix: ${{ fromJSON(needs.pre-distribute.outputs.matrix) }}
    runs-on: ${{ matrix.runs-on }}
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0

      - id: platform
        name: Detect platform
        run: |
          echo "is_android=${{ matrix.platform == 'android' }}" >> $GITHUB_OUTPUT
          echo "is_ios=${{ matrix.platform == 'ios' }}" >> $GITHUB_OUTPUT

      - name: Setup Java
        if: ${{ steps.platform.outputs.is_android }}
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "zulu"

      - name: Setup Android SDK
        if: ${{ steps.platform.outputs.is_android }}
        uses: android-actions/setup-android@v2

      - name: Retrieve Flutter version from FVM config
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Install dependencies
        run: flutter pub get
        
      - name: Install Ruby to use Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: ${{ matrix.working-directory }}

      - name: Get Android secrets files
        if: ${{ steps.platform.outputs.is_android }}
        run: base64 -d <<< ${{ secrets.ANDROID_BUILD_FILES }} | tar xzf -

      - name: Get iOS secrets files
        if: ${{ steps.platform.outputs.is_ios }}
        run: base64 -d <<< ${{ secrets.IOS_BUILD_FILES }} | tar xzf -

      - name: Run lane to distribute
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: ${{ needs.pre-distribute.outputs.lane }}
          options: '{ "tester_email": "${{ secrets.TESTER_EMAIL }}" }'
          subdirectory: ${{ matrix.working-directory }}
        env:
          ZAPIFY_AMPLITUDE_KEY: ${{ secrets.AMPLITUDE_KEY }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  pre-distribute:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.definition.outputs.matrix }}
      lane: ${{ steps.lane.outputs.name }}
    env:
      ENVIRONMENT: ${{ inputs.environment }}
      PLATFORM: ${{ inputs.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0

      - id: lane
        name: Define lane
        run: |
          case "$ENVIRONMENT" in
          production) LANE=release_distribute ;;
          firebase-distribution) LANE=firebase_distribute ;;
          *) echo "Invalid environment $ENVIRONMENT"; exit 1 ;;
          esac

          echo "name=$LANE" >> $GITHUB_OUTPUT

      - id: definition
        name: "Prepare distribution"
        run: |
          yaml2json() {
            python -c 'import sys, yaml, json; print(json.dumps(yaml.safe_load(sys.stdin.read())))'
          }

          JQ_EXPR=$(cat <<EOF
            del( .[] | select(.platform != "$PLATFORM" and "$PLATFORM" != "all"))
          EOF
          )
          MATRIX="{ \"include\": $(yaml2json < .github/distribute-platforms.yml | jq -Mc "$JQ_EXPR") }"

          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
