on: [workflow_dispatch]

name: "[Android] Firebase AppDistribution"

jobs:
  firebase-app-distribution-android:
    runs-on: ubuntu-latest
    environment: firebase-distribution
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.5.0

      - name: Setup Flutter SDK
        uses: ./.github/actions/flutter

      - name: Get Google Services and signing files
        run: |
          echo ${{ secrets.GOOGLE_SERVICES }} | base64 -d  | tar xzf -
          echo ${{ secrets.ANDROID_SECRETS }} | base64 -d  | tar xzf -

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "zulu"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install fastlane and try to distribute
        uses: ./.github/actions/fastlane
        with:
          lane: "firebase_distribute"
          working-directory: "./android"
        env:
          zapify_amplitudeKey: ${{ secrets.AMPLITUDE_KEY }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
