name: "Distribute Android Flutter app"

on:
  workflow_call:
    inputs:
      environment:
        description: "Distribution environment"
        type: string
        required: true

    secrets:
      ANDROID_BUILD_FILES:
        required: true
      AMPLITUDE_KEY:
        required: true
      FIREBASE_TOKEN:
        required: true
      TESTER_EMAIL:
        required: false

jobs:
  distribute:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: "zulu"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Install dependencies
        run: flutter pub get

      - name: Install Ruby to use Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: ./android

      - name: Get Android secrets files
        run: base64 -d <<< ${{ secrets.ANDROID_BUILD_FILES }} | tar xzf -

      - name: Run lane to distribute
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: ${{ vars.TARGET_LANE }}
          options: '{ "tester_email": "${{ secrets.TESTER_EMAIL }}" }'
          subdirectory: ./android
        env:
          ZAPIFY_AMPLITUDE_KEY: ${{ secrets.AMPLITUDE_KEY }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FASTLANE_SKIP_UPDATE_CHECK: true
