name: "Distribute App"

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "Build target platform"
        options:
          - android
          - ios
        type: choice
        required: true
      channel:
        description: "Distribution channel"
        options: 
          - firebase_distribute
          - release_distribute
        type: choice
        required: true

    secrets:
      GOOGLE_SERVICES:
        required: false
      ANDROID_SECRETS:
        required: false
      AMPLITUDE_KEY:
        required: false
      FIREBASE_TOKEN:
        required: false

jobs:
  distribute:
    needs: pre-distribute
    strategy:
      matrix: ${{ fromJSON(needs.pre-distribute.outputs.matrix-definition) }}

    runs-on: ${{ matrix.runs-on }}
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.5.0

      - name: Setup Flutter SDK
        uses: ./.github/actions/flutter

      - name: Setup Android SDK
        if: ${{ matrix.platform == 'android' }}
        uses: ./.github/actions/android

      - name: Get secrets files
        run: |
          echo ${{ secrets.GOOGLE_SERVICES }} | base64 -d  | tar xzf -
          echo ${{ secrets.ANDROID_SECRETS }} | base64 -d  | tar xzf -

      - name: Distribute
        uses: ./.github/actions/fastlane
        with:
          lane: ${{ matrix.lane }}
          working-directory: ${{ matrix.working-directory }}
        env:
          zapify_amplitudeKey: ${{ secrets.AMPLITUDE_KEY }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  pre-distribute:
    runs-on: ubuntu-latest
    outputs:
      matrix-definition: ${{ steps.definition.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.5.0

      - id: definition
        name: "Prepare distribution"
        run: |
          CHANNEL=${{ github.event.inputs.channel }}
          PLATFORM=${{ github.event.inputs.platform }}

          case "$CHANNEL" in
          release_distribute) ENVIRONMENT=production ;;
          *) ENVIRONMENT="firebase-distribution" ;;
          esac

          JQ_EXPR=$(cat <<EOF
            del( .[] | select(.platform != "$PLATFORM"))
            | .[] += { environment: "$ENVIRONMENT", lane: "$CHANNEL" }
          EOF
          )
          MATRIX="{ \"include\": $(jq -Mc "$JQ_EXPR" .github/supported-platforms.json) }"

          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
