name: Check Jekyll build for GitHub Pages

on:
  pull_request:
    branches: [ '**' ]
    paths:
      - 'docs/**'
      - 'CHANGELOG.md'
      - '.github/workflows/jekyll-*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

# Allow one concurrent deployment
concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - id: versions
        name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.versions.outputs.ruby }}
          bundler-cache: true
          cache-version: 0
          working-directory: ./docs

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Copy changelog to site root
        id: pages
        run: cp CHANGELOG.md docs/changelog.md

      - name: Build with Jekyll
        working-directory: ./docs
        run: |
          bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}" --destination ../_site
