name: "Distribute app to tester"

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "Build target platform"
        options:
          - android
          - ios
          - all
        type: choice
        required: true
      tester_email:
        description: "Tester email address"
        type: string
        required: true

jobs:
  distribute:
    uses: ./.github/workflows/distribute.yml
    with:
      platform: ${{ github.event.inputs.platform }}
      environment: firebase-distribution
    secrets:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      ANDROID_BUILD_FILES: ${{ secrets.ANDROID_BUILD_FILES }}
      IOS_BUILD_FILES: ${{ secrets.IOS_BUILD_FILES }}
      AMPLITUDE_KEY: ${{ secrets.AMPLITUDE_KEY }}
      TESTER_EMAIL: ${{ github.event.inputs.tester_email }}
